### ISSUE TITLE
Migrate from GitLab CI to GitHub Actions

### ISSUE THREAD

**Issue by neelkamath** [neelkamath/spacy-server#48]
1. Create a GitHub Actions workflow based on [`.gitlab-ci.yml`](https://github.com/neelkamath/spacy-server/blob/master/.gitlab-ci.yml). Name the workflow `.github/workflows/workflow.yml`. The workflow should run on pushes to the `master` branch, and on pull requests. Here's an example snippet:

    ```yaml
    on:
      push:
        branches: [ master ]
      pull_request:
    ```
2. Delete the GitLab CI file.

If you'd like to work on this, leave a comment saying something like "I'll work on this.", and you can begin without waiting for me to OK it. The point of writing the comment is to let others know that this issue has already been taken up.
